 SUBROUTINE SR016()
	IMPLICIT NONE
!	Subroutine to generate CPMD input file
! 	inputfile is a CHAR variable to store input file name
!   NELMTS : vector contain the number of each chemical element symbols in the PTABLE vector
!   ELMTS :  total number of chemical element symbols in the PTABLE vector
!	PTABLE : vector contains the chemical element symbols
! 	The input file must have the following format

! 	  5
!     Comment line (this line should be present for subroutine works properly)
!     P     0.112   -0.092    0.064  
!     O     0.112    1.475   -0.490  
!     O     1.470   -0.876   -0.490  
!     O    -1.246   -0.876   -0.490  
!     O     0.112   -0.092    1.727  
	
	LOGICAL :: EXISTE 
	REAL :: LatA, LatB, LatC, CosA, CosB, CosC
	INTEGER :: Natoms,ELMTS=17,charge,Cutoff,DUAL,I,J
	CHARACTER(LEN=40) :: InputFile,prefix,outfile1,outfile2,outfile3,outfile4
	CHARACTER(LEN=2),DIMENSION(17) :: PTABLE=(/'H ','Li','C ','N ','O ','F ',&
											'Na','P ','S ','Cl','Ca','Co','Cu',&
											'Br','Kr','Ru','Fe'/)
	CHARACTER(LEN=1),DIMENSION(17) :: ANG=(/'S','S','P','P','P','P','P','D','D',&
											'D','D','D','D','D','D','D','D'/)
	INTEGER, DIMENSION(17) :: NELMTS=(/0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0/)
	CHARACTER(LEN=2), ALLOCATABLE :: SYMBOLS(:)
	REAL, ALLOCATABLE :: Cxyz(:,:)
	
	WRITE(*,'(A)') 'Enter the input file name in the cartesian coordinates'
	READ(*,*) InputFile
	
	INQUIRE(FILE=TRIM(InputFile),EXIST=EXISTE)
	IF(EXISTE) THEN
		OPEN(90,FILE=InputFile,ACTION='READ',STATUS='OLD')
	ELSE
		WRITE(*,*)
		WRITE(*,'(A,A,A)') 'The file ',InputFile,' was not found in this directory'
		STOP
	END IF
! 	>>>>>>> reading the number of atoms <<<<<<<<
	READ(90,*) Natoms
	ALLOCATE(Cxyz(Natoms,3),SYMBOLS(Natoms))
!	>>>>>>> reading the element symbols on the system and their coordinates <<<<<<<<<<
	READ(90,*) SYMBOLS(1)
	DO I=1,Natoms
		READ(90,*) SYMBOLS(I),(Cxyz(I,J),J=1,3)
	END DO
!   >>>>>>>>>>>>>> getting the number of each different atoms in the system <<<<<<<<<<<<
		DO I=1,ELMTS
			DO J=1,Natoms
				IF(PTABLE(I) == SYMBOLS(J)) THEN
					NELMTS(I) = NELMTS(I) + 1
				END IF
			END DO
			IF(NELMTS(I) /= 0) THEN
				WRITE(*,'(A,I3,A,A)') 'THERE ARE ',NELMTS(I),' ',PTABLE(I)
			END IF
		END DO
! >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	WRITE(*,'(A)') 'Enter the prefix name to generate the cpmd input files'
	READ(*,*) prefix
	outfile1=TRIM(prefix)//'-wfnop.inp'
	outfile2=TRIM(prefix)//'-eq.inp'
	outfile3=TRIM(prefix)//'-sim.inp'
    outfile4=TRIM(prefix)//'-BOMD.inp'
	OPEN(91,FILE=outfile1,ACTION='WRITE',STATUS='REPLACE')
	OPEN(92,FILE=outfile2,ACTION='WRITE',STATUS='REPLACE')
	OPEN(93,FILE=outfile3,ACTION='WRITE',STATUS='REPLACE')
    OPEN(94,FILE=outfile4,ACTION='WRITE',STATUS='REPLACE')
	
	WRITE(*,*) 'Enter the charge on the system'
	READ(*,*)   charge
	WRITE(*,*) 'Enter the parameters of the cell: a,b,c, cosA,cosB, and cosC in the same line'
	READ(*,*)   LatA, LatB, LatC, CosA, CosB, CosC
	WRITE(*,*) 'Enter the cutoff energy in Ry to expand the wavefuction in plane wave basis set'
	READ(*,*)   Cutoff
	WRITE(*,*) 'Enter the DUAL for charge density expansion in plane wave basis set'
	READ(*,*)   DUAL

!	>>>>>>> Input for wavefunction optmization <<<<<<<	
	
	WRITE(91,'(A)') '&INFO'
    WRITE(91,'(1X,A)') 'WAVEFUNCTION FUNCTION OPTIMIZATION / GENERATED BY gqtea PROGRAM'
    WRITE(91,*)
    WRITE(91,'(A)') '&END'
    WRITE(91,*)
    WRITE(91,'(A)') '&CPMD'
    WRITE(91,*)
    WRITE(91,'(2X,A)') 'OPTIMIZE WAVEFUNCTION'
    WRITE(91,'(2X,A)') 'CONVERGENCE ORBITALS'
    WRITE(91,'(2X,A)') '1.0d-7'
    WRITE(91,'(2X,A)') 'CENTER MOLECULE ON'
    WRITE(91,'(2X,A)') 'PRINT FORCES ON'
    WRITE(91,'(2X,A)') 'MEMORY BIG'
    WRITE(91,*)
    WRITE(91,'(2X,A)') 'SPLINE POINTS'
    WRITE(91,'(2X,A)') '5000'
    WRITE(91,*)
    WRITE(91,'(2X,A)') 'ODIIS'
    WRITE(91,'(2X,A)') '10'  
    WRITE(91,'(A)') '&END'
    WRITE(91,*)
    WRITE(91,'(A)') '&DFT'
    WRITE(91,'(1X,A)') 'NEWCODE'
    WRITE(91,'(1X,A)') 'FUNCTIONAL PBE'
    WRITE(91,'(A)') '&END'
    WRITE(91,*)
    WRITE(91,'(A)') '&SYSTEM'
    WRITE(91,'(1X,A)') 'CHARGE'
    WRITE(91,'(1X,I3)') charge
    WRITE(91,'(1X,A)') 'SYMMETRY'
    WRITE(91,'(1X,A)') '1'
    WRITE(91,'(1X,A)') 'ANGSTROM'
    WRITE(91,'(1X,A)') 'CELL'
    WRITE(91,'(1X,6F7.2)') LatA,LatB/LatA,LatC/LatA,CosA,CosB,CosC
    WRITE(91,*)  
    WRITE(91,'(1X,A)') 'CUTOFF'
    WRITE(91,'(I4)') Cutoff
    WRITE(91,*)
    WRITE(91,'(1X,A)') 'DUAL'
    WRITE(91,'(I4)') DUAL
    WRITE(91,'(A)') '&END'
    WRITE(91,'(A)') '&ATOMS'

	DO I=1,ELMTS
		IF(NELMTS(I)/= 0) THEN
			WRITE(91,'(A)')'*'//TRIM(PTABLE(I))//'_VDB_PBE.psp FORMATTED'
			WRITE(91,'(A,A)')'LMAX=',ANG(I)
			WRITE(91,'(I3)') NELMTS(I)

			DO J=1,Natoms
				IF(PTABLE(I) == SYMBOLS(J)) THEN
					WRITE(91,'(3F14.5)') Cxyz(J,1),Cxyz(J,2),Cxyz(J,3)
				END IF
			END DO
		ELSE 
			CYCLE
		END IF
		WRITE(91,*)
	END DO

    WRITE(91,'(A)') '&END'
    
!	>>>>>>> Input for BOMD simulation <<<<<<<	
	
	WRITE(94,'(A)') '&INFO'
    WRITE(94,'(1X,A)') 'BOMD SIMULATION INPUT GENERATED BY gqtea PROGRAM'
    WRITE(94,*)
    WRITE(94,'(A)') '&END'
    WRITE(94,*)
    WRITE(94,'(A)') '&CPMD'
    WRITE(94,*)
    WRITE(94,'(2X,A)') 'MOLECULAR DYNAMICS BO'
    WRITE(94,'(2X,A)') 'CONVERGENCE ORBITALS'
    WRITE(94,'(2X,A)') '1.0d-6'
    WRITE(94,'(2X,A)') 'CENTER MOLECULE ON'
    WRITE(94,'(2X,A)') 'PRINT FORCES ON'
    WRITE(94,'(2X,A)') 'MEMORY BIG'
    WRITE(94,'(2X,A)') 'LSD'
    WRITE(94,*)
    WRITE(94,'(2X,A)') 'TRAJECTORY SAMPLE XYZ'
    WRITE(94,'(2X,A)') ' 3'
    WRITE(94,'(2X,A)') 'MAXSTEP'
    WRITE(94,'(2X,A)') '1'
    WRITE(94,'(2X,A)') 'TIMESTEP'
    WRITE(94,'(2X,A)') '3.0'
    WRITE(94,'(2X,A)') 'PCG MINIMIZE'
    WRITE(94,'(2X,A)') 'TIMESTEP'
    WRITE(94,'(2X,A)') '20'
    WRITE(94,*)
 
    WRITE(94,'(A)') '&END'
    WRITE(94,*)
    WRITE(94,'(A)') '&DFT'
    WRITE(94,'(1X,A)') 'XC_DRIVER'
    WRITE(94,'(1X,A)') 'FUNCTIONAL GGA_XC_PBE'
    WRITE(94,'(A)') '&END'
    WRITE(94,*)
    WRITE(94,'(A)') '&SYSTEM'
    WRITE(94,'(1X,A)') 'CHARGE'
    WRITE(94,'(1X,I3)') charge
    WRITE(94,'(1X,A)') 'SYMMETRY'
    WRITE(94,'(1X,A)') '1'
    WRITE(94,'(1X,A)') 'ANGSTROM'
    WRITE(94,'(1X,A)') 'CELL'
    WRITE(94,'(1X,6F7.2)') LatA,LatB/LatA,LatC/LatA,CosA,CosB,CosC
    WRITE(94,*)  
    WRITE(94,'(1X,A)') 'CUTOFF'
    WRITE(94,'(I4)') Cutoff
    WRITE(94,*)
    WRITE(94,'(1X,A)') 'DUAL'
    WRITE(94,'(I4)') DUAL
    WRITE(94,'(A)') '&END'
    WRITE(94,'(A)') '&ATOMS'

	DO I=1,ELMTS
		IF(NELMTS(I)/= 0) THEN
			WRITE(94,'(A)')'*'//TRIM(PTABLE(I))//'_VDB_PBE.psp FORMATTED'
			WRITE(94,'(A,A)')'LMAX=',ANG(I)
			WRITE(94,'(I3)') NELMTS(I)

			DO J=1,Natoms
				IF(PTABLE(I) == SYMBOLS(J)) THEN
					WRITE(94,'(3F14.5)') Cxyz(J,1),Cxyz(J,2),Cxyz(J,3)
				END IF
			END DO
		ELSE 
			CYCLE
		END IF
		WRITE(94,*)
	END DO

    WRITE(94,'(A)') '&END'

!   >>>>>> Inputs for system equilibration and simulation production <<<<<<<<<<
    
	WRITE(92,'(A)') '&INFO'
	WRITE(93,'(A)') '&INFO'
    WRITE(92,'(1X,A)') 'Input file created by gqtea program'
    WRITE(93,'(1X,A)') 'Input file created by gqtea program'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&END'
    WRITE(93,'(A)') '&END'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&CPMD'
    WRITE(93,'(A)') '&CPMD'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'MOLECULAR DYNAMICS CP'
    WRITE(93,'(2X,A)') 'MOLECULAR DYNAMICS CP'
    WRITE(92,'(2X,A)') 'RESTART WAVEFUNCTION COORDINATES LATEST'
    WRITE(93,'(2X,A)') 'RESTART WAVEFUNCTION COORDINATES VELOCITIES NOSEP NOSEE LATEST'
    WRITE(92,'(2X,A)') 'PRINT FORCES ON'
    WRITE(92,'(2X,A)') 'MEMORY BIG'
    WRITE(93,'(2X,A)') 'MEMORY BIG'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'TRAJECTORY SAMPLE XYZ'
    WRITE(93,'(2X,A)') 'TRAJECTORY SAMPLE XYZ'
    WRITE(92,'(2X,A)') ' 5'
    WRITE(93,'(2X,A)') ' 5'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'RESTFILE'
    WRITE(93,'(2X,A)') 'RESTFILE'
    WRITE(92,'(2X,A)') ' 1'
    WRITE(93,'(2X,A)') ' 1'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'STORE'
    WRITE(93,'(2X,A)') 'STORE'
    WRITE(92,'(2X,A)') '200'
    WRITE(93,'(2X,A)') '200'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'MAXSTEP'
    WRITE(93,'(2X,A)') 'MAXSTEP'
    WRITE(92,'(2X,A)') '1000'
    WRITE(93,'(2X,A)') '300000'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'TIMESTEP'
    WRITE(93,'(2X,A)') 'TIMESTEP'
    WRITE(92,'(2X,A)') '5.0'
    WRITE(93,'(2X,A)') '5.0'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'NOSE IONS MASSIVE'
    WRITE(93,'(2X,A)') 'NOSE IONS MASSIVE'
    WRITE(92,'(2X,A)') '300.0 2000.0'
    WRITE(93,'(2X,A)') '300.0 2000.0'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'NOSE ELECTRONS'
    WRITE(93,'(2X,A)') 'NOSE ELECTRONS'
    WRITE(92,'(2X,A)') '0.007 15000.0'
    WRITE(93,'(2X,A)') '0.007 15000.0'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(2X,A)') 'NOSE PARAMETERS'
    WRITE(93,'(2X,A)') 'NOSE PARAMETERS'
    WRITE(92,'(2X,A)') '3 3 3 6.0D0 15 4'
    WRITE(93,'(2X,A)') '3 3 3 6.0D0 15 4'
    WRITE(92,*)
    WRITE(93,*)
    
    WRITE(92,'(2X,A)') 'SPLINE POINTS'
    WRITE(93,'(2X,A)') 'SPLINE POINTS'
    WRITE(92,'(2X,A)') '5000'
    WRITE(93,'(2X,A)') '5000'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&END'
    WRITE(93,'(A)') '&END'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&DFT'
    WRITE(93,'(A)') '&DFT'
    WRITE(92,'(1X,A)') 'NEWCODE'
    WRITE(93,'(1X,A)') 'NEWCODE'
    WRITE(92,'(1X,A)') 'FUNCTIONAL PBE'
    WRITE(93,'(1X,A)') 'FUNCTIONAL PBE'
    WRITE(92,'(A)') '&END'
    WRITE(93,'(A)') '&END'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&SYSTEM'
    WRITE(93,'(A)') '&SYSTEM'
    WRITE(92,'(1X,A)') 'CHARGE'
    WRITE(93,'(1X,A)') 'CHARGE'
    WRITE(92,'(1X,I2)') charge
    WRITE(93,'(1X,I2)') charge
    WRITE(92,'(1X,A)') 'SYMMETRY'
    WRITE(93,'(1X,A)') 'SYMMETRY'
    WRITE(92,'(1X,A)') ' 1'
    WRITE(93,'(1X,A)') ' 1'
    WRITE(92,'(1X,A)') 'ANGSTROM'
    WRITE(93,'(1X,A)') 'ANGSTROM'
    WRITE(92,'(1X,A)') 'CELL'
    WRITE(93,'(1X,A)') 'CELL'
    WRITE(92,'(1X,6F7.2)')  LatA,LatB/LatA,LatC/LatA,CosA,CosB,CosC
    WRITE(93,'(1X,6F7.2)')  LatA,LatB/LatA,LatC/LatA,CosA,CosB,CosC
    WRITE(92,*)  
    WRITE(93,*)  
    WRITE(92,'(1X,A)') 'CUTOFF'
    WRITE(93,'(1X,A)') 'CUTOFF'
    WRITE(92,'(I4)') Cutoff
    WRITE(93,'(I4)') Cutoff
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(1X,A)') 'DUAL'
    WRITE(93,'(1X,A)') 'DUAL'
    WRITE(92,'(I4)') DUAL
    WRITE(93,'(I4)') DUAL
    WRITE(92,'(A)') '&END'
    WRITE(93,'(A)') '&END'
    WRITE(92,*)
    WRITE(93,*)
    WRITE(92,'(A)') '&ATOMS'
    WRITE(93,'(A)') '&ATOMS'
    DO I=1,ELMTS
	    IF(NELMTS(I)/= 0) THEN
	    	WRITE(92,'(A)')'*'//TRIM(PTABLE(I))//'_VDB_PBE.psp FORMATTED'
	    	WRITE(93,'(A)')'*'//TRIM(PTABLE(I))//'_VDB_PBE.psp FORMATTED'
	    	WRITE(92,'(A,A)')'LMAX=',ANG(I)
	    	WRITE(92,'(I3)') NELMTS(I)
	    	WRITE(93,'(A,A)')'LMAX=',ANG(I)
	    	WRITE(93,'(I3)') NELMTS(I)

	    	DO J=1,Natoms
	    		IF(PTABLE(I) == SYMBOLS(J)) THEN
	    			WRITE(92,'(3F14.5)') Cxyz(J,1),Cxyz(J,2),Cxyz(J,3)
	    			WRITE(93,'(3F14.5)') Cxyz(J,1),Cxyz(J,2),Cxyz(J,3)
	    		END IF
	    	END DO
	    ELSE 
	    	CYCLE
	    END IF
	    WRITE(92,*)
	    WRITE(93,*)
    END DO
    WRITE(92,'(A)') '&END'
    WRITE(93,'(A)') '&END'
    CLOSE(90)
    CLOSE(91)
    CLOSE(92)
    CLOSE(93)

 END SUBROUTINE SR016