SUBROUTINE SR027()
IMPLICIT NONE

INTEGER :: option

100	WRITE(*,'(A)') ' 1 - GENERATE CPMD INPUT FILE'
	WRITE(*,'(A)') ' '
	WRITE(*,'(A)') ' 2 - INITIAL VELOCITY SETUP FOR COLLISION SIMULATION IN CPMD'
	READ(*,*) option
  
	SELECT CASE(option)
		CASE(1)
			CALL SR016()
		CASE(2)
			CALL SR028() 
		CASE DEFAULT
			WRITE(*,*) 'CHOOSE A VALID OPTION'
			GO TO 100
	END SELECT
	
END SUBROUTINE SR027