SUBROUTINE SR028()
IMPLICIT NONE

LOGICAL :: EXISTE
INTEGER :: totNumAtoms,I,J,K,nAtomsRover
CHARACTER(LEN=2),DIMENSION(6):: pTable=(/'H ','C ','N ','O ','F ','Br'/)
REAL, DIMENSION(6) :: atomicMass=(/1.00794,12.011,14.0674,15.9994,18.9994,79.904/)
CHARACTER(LEN=2),ALLOCATABLE :: atomSymbol(:)
CHARACTER(LEN=175) :: line
INTEGER,ALLOCATABLE :: labelsRover(:)
REAL :: tmpVelX,tmpVelY,tmpVelZ,innerProd,scaleFactor,&
        speedAU,speedMS,initialVel,molWeight=0.0,kinectEnergy,&
        targetX,targetY,targetZ
REAL, ALLOCATABLE:: posVel(:,:)

WRITE(*,*) 'This subroutine setup the initial velocity'
WRITE(*,*) 'for the rover molecule in the collision molecular'
WRITE(*,*) 'dynamics simulation using the CPMD program. It uses '
WRITE(*,*) 'as input the GEOMETRY.xyz file obtained from cpmd.x after' 
WRITE(*,*) 'run 1 step of simulation. A new file called GEOMETRY is then' 
WRITE(*,*) 'generated by this subroutine, and the cpmd.x program is restarted'
WRITE(*,*) 'with this new file using the following keywords:'
WRITE(*,*) 'RESTART WAVEFUNCTION COORDINATES VELOCITIES GEOFILE LATEST'
WRITE(*,*)

INQUIRE(FILE=TRIM('GEOMETRY.xyz'),EXIST=EXISTE)
IF(EXISTE) THEN
  OPEN(10,FILE='GEOMETRY.xyz',ACTION='READ',STATUS='OLD')
  OPEN(11,FILE='GEOMETRY',ACTION='WRITE',STATUS='REPLACE')
  OPEN(12,FILE='summary.txt',ACTION='WRITE',STATUS='REPLACE')
ELSE
  WRITE(*,*)
  WRITE(*,'(A)') 'The file GEOMETRY.xyz was not found in the same folder'
  WRITE(*,'(A)') 'as the program'
  STOP
END IF
WRITE(*,*) 'How many atoms does molecule rover have?'
READ(*,*) nAtomsRover
ALLOCATE(labelsRover(nAtomsRover))
WRITE(*,*) 'Enter the atom labels of the rover molecule'
DO I=1,nAtomsRover
  WRITE(*,'(A6,I3)') 'Label ',I
  READ(*,*) labelsRover(I)
END DO
WRITE(*,*) 'Enter the target position X, Y, and Z'
WRITE(*,*) 'e.g.  -2.352 0.185 3.861'
READ(*,*) targetX,targetY,targetZ 
WRITE(*,*) 'Enter the initial velocity in atomic units'
READ(*,*) initialVel
READ(10,*) totNumAtoms
READ(10,*) line
ALLOCATE(atomSymbol(totNumAtoms),posVel(totNumAtoms,6))
DO I=1,totNumAtoms
   READ(10,*) atomSymbol(I), (posVel(I,J),J=1,6)
END DO
WRITE(*,*) totNumAtoms
WRITE(*,*) 'ORIGINAL GEOMETRY.xyz FILE'
DO I=1,totNumAtoms
   WRITE(*,'(I3,A4,6F14.7)') I,atomSymbol(I), (posVel(I,J),J=1,6)
END DO

DO I=1,nAtomsRover
  DO J=1,totNumAtoms
    IF(labelsRover(I) == J) THEN
      tmpVelX = targetX - posVel(J,1)
      tmpVelY = targetY - posVel(J,2)
      tmpVelZ = targetZ - posVel(J,3)
      innerProd = tmpVelX**2 + tmpVelY**2 + tmpVelZ**2
      scaleFactor = initialVel/SQRT(innerProd)
      posVel(J,4) = scaleFactor*tmpVelX
      posVel(J,5) = scaleFactor*tmpVelY
      posVel(J,6) = scaleFactor*tmpVelZ
      speedAU = SQRT(posVel(J,4)**2 + posVel(J,5)**2 + posVel(J,6)**2)
      speedMS = speedAU*2.18769126379E6
      WRITE(12,'(A,I2,A,ES14.7,A6,ES14.7,A)') 'Speed of atom ',labelsRover(I), &
               '..............',speedAU,'au or ',speedMS,' m/s'
    END IF
  END DO
END DO
DO I=1,totNumAtoms
  posVel(I,1)=posVel(I,1)/0.52917720859
  posVel(I,2)=posVel(I,2)/0.52917720859
  posVel(I,3)=posVel(I,3)/0.52917720859
END DO
DO I=1,totNumAtoms
  WRITE(11,'(6F14.7)') (posVel(I,J),J=1,6)
END DO
WRITE(*,*) 'GEOMETRY IN ATOMIC UNIT'
DO I=1,totNumAtoms
  WRITE(*,'(I3,A4,6F14.7)') I,atomSymbol(I), (posVel(I,J),J=1,6)
END DO
!Writting initial kinect energy
DO I=1,nAtomsRover
  DO J=1,totNumAtoms
    IF(labelsRover(I) == J) THEN
      DO K=1,6
        IF(atomSymbol(J) == pTable(K)) THEN
          molWeight = molWeight + atomicMass(K)
        END IF
      END DO
    END IF
  END DO
END DO
kinectEnergy = (molWeight*speedMS**2)/(2.0*1000)
WRITE(12,'(A,F11.7,A)') 'Rover molecular weight ...... ',molWeight, ' g/mol'
WRITE(12,'(A,ES14.7,A)') 'Kinect energy................ ',kinectEnergy,' J/mol'
kinectEnergy=kinectEnergy/4184.0
WRITE(12,'(A,ES14.7,A)') 'Kinect energy................ ',kinectEnergy,' kcal/mol'
WRITE(12,'(A,3F8.5)')    'Target postition............. ',targetX,targetY,targetZ
CLOSE(10)
CLOSE(11)
CLOSE(12)

END SUBROUTINE SR028